spring.application.name=Healthcare
# Server port configuration
server.port=8080

# LangChain4j routing to Groq's OpenAI-compatible endpoint
langchain4j.open-ai.chat-model.base-url=https://api.groq.com/openai/v1
langchain4j.open-ai.chat-model.api-key=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
langchain4j.open-ai.chat-model.model-name=llama-3.1-8b-instant
langchain4j.open-ai.chat-model.temperature=0.2
